### ISSUE TITLE
How to skip resolving plugin in production?

### ISSUE THREAD

**Issue by alexanderzone** [JimmyBeldone/gatsby-plugin-webpack-bundle-analyser-v2#260]
Install instructions mark this as a dev dependency. When I'm building production, this package isnt installed, and so my `gatsby-config` fails to resolve `gatsby-plugin-webpack-bundle-analyser-v2`.

Is there a way to mark the plugin as dev only in my `gatsby-config`? Or how should I fix this? Thanks for your help

**Comment by alexanderzone** [comment]
I ended up using logic that basically did `if development, then concat my devPlugins to the plugins array`

If there is a better way to do this I would love to know, since the docs made it seem like this should just work

**Comment by JimmyBeldone** [comment]
Hey @aamistak, sorry for the late answer, I don't have much time to spend on side projects this last two months.

Most of the time you can use webpack-bundle-analyzer locally when running `gatsby build` so that you just need it as a devDependency, but if you really need to provide a stat file on your production server I suggest you install it as a dependency. 

On my many projects I install all dependencies on my CI server, including devDependencies for testing, and then the CI server deploys my `/public` directory to my production server, so my plugin is resolved, and my stat file is present in production.

Could you provide a code example or a context of your production stack / process please ?

What are you trying to do exactly ?

**Comment by alexanderzone** [comment]
I do not need to provide a stat file on my production server. The problem is that gatsby config seeks the webpack-analyzer plugin regardless if it is a dev environment or not, which causes my non-dev builds to fail.

I solved this in an adhoc way by only including dev plugins like this one into my gatsby config if I was in a dev environment. I was only wondering if there was a more elegant way to do this with Gatsby (e.g. by marking plugins dev-only), but it seems like there is not. Maybe worth a line in the setup docs. No worries if not!
