### ISSUE TITLE
Analyser is running in a production build

### ISSUE THREAD

**Issue by xenostar** [JimmyBeldone/gatsby-plugin-webpack-bundle-analyser-v2#292]
I just built my personal site on Netlify and noticed this in the build logs:

> 7:58:06 PM: Webpack Bundle Analyzer is started at http://127.0.0.1:3002
7:58:06 PM: Use Ctrl+C to close it

This doesn't seem like intended behavior. I have it configured like so in my `gatsby-config.js`:

```
    {
      resolve: `gatsby-plugin-webpack-bundle-analyser-v2`,
      options: {
        devMode: false,
        analyzerPort: 3002
      }
    }
```

And it _is_ installed as a devDependency:

```
"devDependencies": {
    "gatsby-plugin-webpack-bundle-analyser-v2": "^1.1.12"
}
```

Does this seem like a bug? I notice this same message occurs when running `gatsby build` locally.

**Comment by JimmyBeldone** [comment]
Hi @xenostar, 

This isn't a bug :) 

This plugin is supposed to run in production, the purpose of Webpack Bundle Analyzer is to _"Visualize size of webpack output files with an interactive zoomable treemap"_.

The `devMode` option only activate / deactivate plugin if Gatsby `stage === 'develop'`, but it will run on `stage === 'build-javascript'`.

If you don't want it to to run at all in production, you can set `disable` option to true, or `disable: process.env.NODE_ENV === 'production'`

Concerning the devDependencies and Netlify, I agree with you it seems like a bug, but it is not ^^ 
The reason is, before running `gatsby build`command, Netlify pull your code from your git, and then it has to install your dependencies, using `yarn` or `npm install` command. 
These commands, unless used with a production flag (`yarn --production`), will install `dependencies` AND `devDependencies`.

I hope it was helpful ;)

**Comment by xenostar** [comment]
Thanks for the explanations Jimmy! And thank for your the `process.env` trick, that is super cool. Definitely adding that to my configuration files.

**Comment by JimmyBeldone** [comment]
My pleasure ;) 
I close the issue then.
